version: '2'

services:
   db:
     image: mysql:5.7
     volumes:
       - db_data:/var/lib/mysql
     restart: always
     environment:
       MYSQL_ROOT_PASSWORD: ${MYSQL_DATABASE_PASSWORD}
       MYSQL_DATABASE: wordpress
       MYSQL_USER: wordpress
       MYSQL_PASSWORD: wordpress

   wordpress:
     image: wordpress:latest
     ports:
       - 80
     restart: always
     environment:
       WORDPRESS_DB_HOST: db:3306
       WORDPRESS_DB_USER: wordpress
       WORDPRESS_DB_PASSWORD: wordpress
     labels:
      traefik.docker.network: traefik-proxy
      traefik.enable: true
      traefik.http.middlewares.vespa-https-redirect.redirectscheme.scheme: https
      traefik.http.routers.vespa-secure.entrypoints: https
      traefik.http.routers.vespa-secure.rule: Host(\`vespa.thievent.org\`)
      traefik.http.routers.vespa-secure.service: vespa
      traefik.http.routers.vespa-secure.tls: true
      traefik.http.routers.vespa-secure.tls.certresolver: http
      traefik.http.routers.vespa.entrypoints: http
      traefik.http.routers.vespa.middlewares: vespa-https-redirect
      traefik.http.routers.vespa.rule: Host(\`vespa.thievent.org\`)
      traefik.http.services.vespa.loadbalancer.server.port: 80

volumes:
    db_data:
